[runtime]
entity_type = "service"
service_name = "certification_server"
instance_id = "certification_server"
run_mode = "no_auth"
grpc_listen_port = 50051

[auth]
secret_key_dir = "secret_keys"
active_key_id = "cert-local-key"