[runtime]
entity_type = "service"
service_name = "gateway"
instance_id = "gateway"
run_mode = "no_auth"
http_listen_port = 8080

[auth]
secret_key_dir = "secret_keys"
active_key_id = "gateway-local-key"

