from enum import Enum


class ErrorCode(str, Enum):
    INVALID_REQUEST = "INVALID_REQUEST"
    INTENT_FAILED = "INTENT_FAILED"
    PLAN_FAILED = "PLAN_FAILED"
    TOOL_NOT_FOUND = "TOOL_NOT_FOUND"
    TOOL_EXECUTION_FAILED = "TOOL_EXECUTION_FAILED"
    PROVIDER_TIMEOUT = "PROVIDER_TIMEOUT"
    PROVIDER_RATE_LIMIT = "PROVIDER_RATE_LIMIT"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    RAG_FAILED = "RAG_FAILED"
    SYNTHESIS_FAILED = "SYNTHESIS_FAILED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
