-- 认证中心认证/通信安全表结构（MySQL 8.0+）

CREATE TABLE IF NOT EXISTS auth_token_records (
  id CHAR(36) NOT NULL,
  raw_token VARCHAR(512) NOT NULL,
  family_id CHAR(36) NOT NULL,
  session_id CHAR(36) NOT NULL,
  token_type VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  storage VARCHAR(32) NOT NULL,
  principal_type VARCHAR(32) NOT NULL,
  principal_id VARCHAR(128) NOT NULL,
  parent_token_id CHAR(36) NULL,
  client_id VARCHAR(128) NOT NULL,
  gateway_id VARCHAR(128) NOT NULL,
  role_snapshot VARCHAR(64) NOT NULL,
  scope_snapshot JSON NOT NULL,
  issued_at DATETIME(3) NOT NULL,
  expires_at DATETIME(3) NOT NULL,
  last_validated_at DATETIME(3) NULL,
  revoked_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_auth_token_raw (raw_token),
  KEY idx_auth_token_family (family_id),
  KEY idx_auth_token_session (session_id),
  KEY idx_auth_token_status_exp (status, expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS auth_token_claims (
  token_id CHAR(36) NOT NULL,
  issuer VARCHAR(128) NOT NULL,
  audience VARCHAR(128) NOT NULL,
  subject VARCHAR(128) NOT NULL,
  token_type VARCHAR(32) NOT NULL,
  entity_type VARCHAR(32) NOT NULL,
  entity_id VARCHAR(128) NOT NULL,
  principal_id VARCHAR(160) NOT NULL,
  session_id CHAR(36) NOT NULL,
  family_id CHAR(36) NOT NULL,
  parent_id CHAR(36) NULL,
  role VARCHAR(64) NOT NULL,
  scopes JSON NOT NULL,
  auth_method VARCHAR(64) NOT NULL,
  client_id VARCHAR(128) NOT NULL,
  gateway_id VARCHAR(128) NOT NULL,
  source_service VARCHAR(128) NOT NULL,
  target_service VARCHAR(128) NOT NULL,
  issued_at DATETIME(3) NOT NULL,
  expires_at DATETIME(3) NOT NULL,
  PRIMARY KEY (token_id),
  KEY idx_auth_claims_session (session_id),
  KEY idx_auth_claims_family (family_id),
  CONSTRAINT fk_auth_claims_token FOREIGN KEY (token_id) REFERENCES auth_token_records(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS auth_service_public_keys (
  key_id VARCHAR(128) NOT NULL,
  owner_type VARCHAR(32) NOT NULL,
  service_id VARCHAR(128) NOT NULL,
  service_name VARCHAR(128) NOT NULL,
  instance_id VARCHAR(128) NOT NULL,
  instance_name VARCHAR(128) NOT NULL,
  key_exchange_algorithm VARCHAR(64) NOT NULL,
  signature_algorithm VARCHAR(64) NOT NULL,
  public_key_pem TEXT NOT NULL,
  fingerprint VARCHAR(256) NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at DATETIME(3) NOT NULL,
  activated_at DATETIME(3) NOT NULL,
  expires_at DATETIME(3) NOT NULL,
  revoked_at DATETIME(3) NULL,
  PRIMARY KEY (key_id),
  KEY idx_auth_pubkey_owner (owner_type, service_id, instance_id),
  KEY idx_auth_pubkey_status_exp (status, expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

