-- 认证中心认证/通信安全表结构（MySQL 8.0+）

CREATE TABLE IF NOT EXISTS auth_token_records (
  id CHAR(36) NOT NULL,
  raw_token VARCHAR(512) NOT NULL,
  family_id CHAR(36) NOT NULL,
  session_id CHAR(36) NOT NULL,
  token_type VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  storage VARCHAR(32) NOT NULL,
  principal_type VARCHAR(32) NOT NULL,
  principal_id VARCHAR(128) NOT NULL,
  parent_token_id CHAR(36) NULL,
  client_id VARCHAR(128) NOT NULL,
  gateway_id VARCHAR(128) NOT NULL,
  role_snapshot VARCHAR(64) NOT NULL,
  scope_snapshot JSON NOT NULL,
  issued_at DATETIME(3) NOT NULL,
  expires_at DATETIME(3) NOT NULL,
  last_validated_at DATETIME(3) NULL,
  revoked_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_auth_token_raw (raw_token),
  KEY idx_auth_token_family (family_id),
  KEY idx_auth_token_session (session_id),
  KEY idx_auth_token_status_exp (status, expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS auth_token_claims (
  token_id CHAR(36) NOT NULL,
  issuer VARCHAR(128) NOT NULL,
  audience VARCHAR(128) NOT NULL,
  subject VARCHAR(128) NOT NULL,
  token_type VARCHAR(32) NOT NULL,
  entity_type VARCHAR(32) NOT NULL,
  entity_id VARCHAR(128) NOT NULL,
  principal_id VARCHAR(160) NOT NULL,
  session_id CHAR(36) NOT NULL,
  family_id CHAR(36) NOT NULL,
  parent_id CHAR(36) NULL,
  role VARCHAR(64) NOT NULL,
  scopes JSON NOT NULL,
  auth_method VARCHAR(64) NOT NULL,
  client_id VARCHAR(128) NOT NULL,
  gateway_id VARCHAR(128) NOT NULL,
  source_service VARCHAR(128) NOT NULL,
  target_service VARCHAR(128) NOT NULL,
  issued_at DATETIME(3) NOT NULL,
  expires_at DATETIME(3) NOT NULL,
  PRIMARY KEY (token_id),
  KEY idx_auth_claims_session (session_id),
  KEY idx_auth_claims_family (family_id),
  CONSTRAINT fk_auth_claims_token FOREIGN KEY (token_id) REFERENCES auth_token_records(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS auth_sessions (
  id CHAR(36) NOT NULL,
  entity_type VARCHAR(32) NOT NULL,
  entity_id VARCHAR(128) NOT NULL,
  principal_id VARCHAR(160) NOT NULL,
  status VARCHAR(32) NOT NULL,
  auth_method VARCHAR(64) NOT NULL,
  created_by_ip VARCHAR(64) NOT NULL,
  last_seen_ip VARCHAR(64) NOT NULL,
  user_agent VARCHAR(256) NOT NULL,
  client_id VARCHAR(128) NOT NULL,
  gateway_id VARCHAR(128) NOT NULL,
  scope_snapshot JSON NOT NULL,
  role_snapshot VARCHAR(64) NOT NULL,
  token_family_id CHAR(36) NOT NULL,
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  last_seen_at DATETIME(3) NOT NULL,
  last_verified_at DATETIME(3) NULL,
  next_refresh_at DATETIME(3) NOT NULL,
  expires_at DATETIME(3) NOT NULL,
  revoked_at DATETIME(3) NULL,
  version BIGINT NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  KEY idx_auth_session_principal (principal_id),
  KEY idx_auth_session_status_exp (status, expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS auth_bootstrap_challenges (
  challenge_id CHAR(36) NOT NULL,
  issuer VARCHAR(128) NOT NULL,
  audience VARCHAR(128) NOT NULL,
  entity_type VARCHAR(32) NOT NULL,
  entity_id VARCHAR(128) NOT NULL,
  key_id VARCHAR(128) NOT NULL,
  nonce VARCHAR(256) NOT NULL,
  issued_at DATETIME(3) NOT NULL,
  expires_at DATETIME(3) NOT NULL,
  PRIMARY KEY (challenge_id),
  KEY idx_auth_bootstrap_exp (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS auth_bootstrap_stages (
  principal_id VARCHAR(160) NOT NULL,
  stage VARCHAR(64) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  PRIMARY KEY (principal_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS auth_service_public_keys (
  key_id VARCHAR(128) NOT NULL,
  owner_type VARCHAR(32) NOT NULL,
  service_id VARCHAR(128) NOT NULL,
  service_name VARCHAR(128) NOT NULL,
  instance_id VARCHAR(128) NOT NULL,
  instance_name VARCHAR(128) NOT NULL,
  key_exchange_algorithm VARCHAR(64) NOT NULL,
  signature_algorithm VARCHAR(64) NOT NULL,
  public_key_pem TEXT NOT NULL,
  fingerprint VARCHAR(256) NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at DATETIME(3) NOT NULL,
  activated_at DATETIME(3) NOT NULL,
  expires_at DATETIME(3) NOT NULL,
  revoked_at DATETIME(3) NULL,
  PRIMARY KEY (key_id),
  KEY idx_auth_pubkey_owner (owner_type, service_id, instance_id),
  KEY idx_auth_pubkey_status_exp (status, expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS auth_commsec_handshakes (
  id CHAR(36) NOT NULL,
  initiator_owner_type VARCHAR(32) NOT NULL,
  initiator_service_id VARCHAR(128) NOT NULL,
  initiator_service_name VARCHAR(128) NOT NULL,
  initiator_instance_id VARCHAR(128) NOT NULL,
  initiator_instance_name VARCHAR(128) NOT NULL,
  responder_owner_type VARCHAR(32) NOT NULL,
  responder_service_id VARCHAR(128) NOT NULL,
  responder_service_name VARCHAR(128) NOT NULL,
  responder_instance_id VARCHAR(128) NOT NULL,
  responder_instance_name VARCHAR(128) NOT NULL,
  initiator_key_id VARCHAR(128) NOT NULL,
  responder_key_id VARCHAR(128) NOT NULL,
  key_exchange_algorithm VARCHAR(64) NOT NULL,
  signature_algorithm VARCHAR(64) NOT NULL,
  cipher_suite VARCHAR(64) NOT NULL,
  initiator_ephemeral_public_key TEXT NOT NULL,
  responder_ephemeral_public_key TEXT NOT NULL,
  initiator_nonce VARCHAR(256) NOT NULL,
  responder_nonce VARCHAR(256) NOT NULL,
  initiator_signature TEXT NOT NULL,
  responder_signature TEXT NOT NULL,
  status VARCHAR(32) NOT NULL,
  failure_reason VARCHAR(512) NOT NULL,
  started_at DATETIME(3) NOT NULL,
  completed_at DATETIME(3) NULL,
  expires_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  KEY idx_auth_handshake_status_exp (status, expires_at),
  KEY idx_auth_handshake_initiator (initiator_service_id),
  KEY idx_auth_handshake_responder (responder_service_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS auth_secure_channels (
  id CHAR(36) NOT NULL,
  handshake_id CHAR(36) NOT NULL,
  binding_type VARCHAR(32) NOT NULL,
  binding_session_id CHAR(36) NULL,
  binding_token_id CHAR(36) NULL,
  binding_family_id CHAR(36) NULL,
  source_owner_type VARCHAR(32) NOT NULL,
  source_service_id VARCHAR(128) NOT NULL,
  source_service_name VARCHAR(128) NOT NULL,
  source_instance_id VARCHAR(128) NOT NULL,
  source_instance_name VARCHAR(128) NOT NULL,
  target_owner_type VARCHAR(32) NOT NULL,
  target_service_id VARCHAR(128) NOT NULL,
  target_service_name VARCHAR(128) NOT NULL,
  target_instance_id VARCHAR(128) NOT NULL,
  target_instance_name VARCHAR(128) NOT NULL,
  local_key_id VARCHAR(128) NOT NULL,
  peer_key_id VARCHAR(128) NOT NULL,
  cipher_suite VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL,
  derived_key_ref VARCHAR(256) NOT NULL,
  seq_no BIGINT UNSIGNED NOT NULL DEFAULT 0,
  established_at DATETIME(3) NOT NULL,
  last_used_at DATETIME(3) NOT NULL,
  expires_at DATETIME(3) NOT NULL,
  revoked_at DATETIME(3) NULL,
  updated_at DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  KEY idx_auth_channel_handshake (handshake_id),
  KEY idx_auth_channel_binding (binding_type, binding_session_id, binding_token_id, binding_family_id),
  KEY idx_auth_channel_status_exp (status, expires_at),
  KEY idx_auth_channel_source_target (source_service_id, target_service_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
